### ISSUE TITLE
creation failed , the directory name is invalid

### ISSUE THREAD

**Issue by bajechele** [redsolver/yt-splitter#1]
if the utube video title contain | this symbol its giving error 

> Unhandled exception:
FileSystemException: Creation failed, path = 'name | Future blast booom' (OS Error: The directory name is invalid.
, errno = 267)
#0      _Directory.createSync (dart:io/directory_impl.dart:133)
#1      main (file:///d:/a/yt-splitter/yt-splitter/bin/yt_splitter.dart:99)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

i think this is bcoz of windows coz by default yt-splitter creates directory and it uses the vdo title as the name of that directory but in windows using | / \ ? " : * < > this characters in naming is locked ... thats why i checked utubedl replaces them with space or _ if the title contains them ....

**Comment by redsolver** [comment]
I just released Version 0.1.2, it should fix this issue: https://github.com/redsolver/yt-splitter/releases/tag/v0.1.2

**Comment by bajechele** [comment]
tested working flawlessly now ... thanks
