### ISSUE TITLE
so many detection virustotal

### ISSUE THREAD

**Issue by bajechele** [redsolver/yt-splitter#2]
got red flag from avast while using it ... i thought its a false positive but virustotal saying different story .. please tell me how to resolve this issue ...  https://www.virustotal.com/gui/file/15ccb77bed38f875a303119a8f677b3c6bde29bbdd9fdf2c0c182cf33af4332c/detection

**Comment by redsolver** [comment]
It's likely a false positive, you can read more about it here: https://www.reddit.com/r/youtubedl/comments/mdv9pv/bitdefender_flags_ytsplitter_as_malware/

**Comment by bajechele** [comment]
just saw that anything thats using dart having this problem ....its ok.. but as u can understand those virustotal results its a mess .....but since u saying its false positive i will use it np... thanks...

**Comment by Coloradohusky** [comment]
Just to add onto this, both Windows Defender, Malwarebytes, and Mozilla Firefox flagged it as malware. Defender says it's `Trojan:Win32/Ymacco.AA15`, and Malwarebytes says it's a generic malware. Weird that this happens for all Dart programs, but I trust your response.

**Comment by redsolver** [comment]
I just compiled a new windows release from exactly the same code but with a new Dart SDK version, looks like that one is not flagged: https://github.com/redsolver/yt-splitter/releases/tag/v0.1.2
