### ISSUE TITLE
The system could not find the specified file

### ISSUE THREAD

**Issue by checon56** [redsolver/yt-splitter#3]
So hey. I've put yt-splitter.exe and ffmpeg.exe in C:/WIndows/System32 but still won't work. Can you help?

[(C:\Users\ADM\Downloads>yt-splitter https://www.youtube.com/watch?v=GwpdmkBUtL8
YT video: GwpdmkBUtL8...
Downloading and converting audio file from YouTube...
CreateProcessW failed 2
Unhandled exception:
ProcessException: O sistema não pode encontrar o arquivo especificado. _(The system could not find the specified file)_ 

  Command: youtube-dl --write-info-json --write-thumbnail --extract-audio --audio-format mp3 --output output.%(ext)s https://www.youtube.com/watch?v=GwpdmkBUtL8
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390)
#1      Process.start (dart:io-patch/process_patch.dart:36)
#2      main (file:///d:/a/yt-splitter/yt-splitter/bin/yt_splitter.dart:42)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184))
]

**Comment by redsolver** [comment]
You also need https://github.com/ytdl-org/youtube-dl

**Comment by checon56** [comment]
Now I got this

Downloading and converting audio file from YouTube...
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
Current thread 0x00003198 (most recent call first):

**Comment by checon56** [comment]
Ok, so I solved now. I was placing all archives in system32. On youtube-dl page says to not put there. So I've copied to C:/Windows and started downloading and splitting. Works now

Thank you for your time. Maybe you should put this on the instructions too
